{{- range $index := .Values.telliot.modes }}
{{- $val := dict "mode" $index }}
{{- $modeName := printf "%s-%s" (include "telliot.fullname" $) (include "telliot.modeName" $val) | trunc 63 | trimSuffix "-" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $modeName }}
data:
{{- $modePath := printf "%s/%s" "files" ((get $val "mode")| lower) }}
{{- $path := "files" }}
{{- $modeConfig := $.Files.Glob (printf "%s/%s" $modePath "config.json") }}
{{- if $modeConfig }}
  config.json: |-
{{ $.Files.Get (printf "%s/%s" $modePath "config.json") | indent 4 }}
{{- else }}
{{ $.Files.Get (printf "%s/%s" $path "config.json") | indent 4 }}
{{- end }}
  index.json: |-
{{ $.Files.Get (printf "%s/%s" $path "index.json") | indent 4 }}
  manualData.json: |-
{{ $.Files.Get (printf "%s/%s" $path "manualData.json") | indent 4 }}
{{- end }}
